# Generated by Django 5.1.2 on 2025-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="neighborhood",
            field=models.CharField(max_length=100, verbose_name="Neighborhood"),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.IntegerField(verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="client",
            name="annotations",
            field=models.TextField(verbose_name="Annotations"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.TextField(verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.TextField(verbose_name="Phone"),
        ),
    ]
