# Generated by Django 5.1.2 on 2025-01-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='client',
            name='annotations',
            field=models.TextField(verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.TextField(verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.TextField(verbose_name='Telefone'),
        ),
    ]
