services:

  postgres:
    image: postgres
    container_name: ams-database
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - ams-network

  application:
    container_name: ams-application
    build: 
      context: ./django/
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./django/:/home/asm/asm/
    links:
      - postgres 
    depends_on:
      - postgres 
    networks:
      - ams-network

volumes:
  database_data:

networks:
  ams-network:
