services:

  application:
    container_name: ams-application
    build: 
      context: ./django/
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./django/:/home/asm/asm/
    networks:
      - ams-network

networks:
  ams-network:
