# Generated by Django 5.1.2 on 2025-01-07 20:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Created At', models.DateTimeField(auto_now_add=True)),
                ('Updated At', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0, message='The Value must be greater than 0')], verbose_name='Base Value')),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Created At', models.DateTimeField(auto_now_add=True)),
                ('Updated At', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0, message='The Value must be greater than 0')], verbose_name='Value')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_Type', to='tasks.tasktype', verbose_name='Task Type')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('description',),
            },
        ),
    ]
