name: CI Pipeline

on:
  push:
  workflow_dispatch:

jobs:

  code-analisys:
    runs-on: ubuntu-latest
    name: Code Analisys

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: ./django/
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-groups

      - name: Linting
        working-directory: ./django/
        run: |
          uv run ruff check .

      - name: Formatting
        working-directory: ./django/
        run: |
          uv run ruff format --check --diff .

      - name: Security Analysis
        working-directory: ./django/
        run: |
          uv run bandit -r .

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    needs: code-analisys

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./django/
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-groups

      - name: Run Unit Tests
        run: |
          uv run pytest 

