name: CI Pipeline

on:
  push:
  workflow_dispatch:

jobs:

  code-analisys:
    runs-on: ubuntu-latest
    name: Code Analisys

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: ./django/
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Linting
        working-directory: ./django/
        run: |
          poetry run ruff check .

      - name: Formatting
        working-directory: ./django/
        run: |
          poetry run ruff format --check --diff .

      - name: Security Analysis
        working-directory: ./django/
        run: |
          poetry run bandit -r .

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    needs: code-analisys

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '2.14.2'

      - name: Run Unit Tests
        run: |
          docker-compose up -d
          docker-compose exec application poetry run pytest

